//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangGia
    {
        public int STT { get; set; }
        public string MaBangGia { get; set; }
        public string MaLoaiXe { get; set; }
        public string MaKH { get; set; }
        public string MaLoTrinh { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string ThoiGian { get; set; }
        public Nullable<decimal> SoKM { get; set; }
        public Nullable<bool> Dang { get; set; }
    
        public virtual LoaiXe LoaiXe { get; set; }
        public virtual LoTrinh LoTrinh { get; set; }
    }
}
