//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiPhiPhatSinh
    {
        public string MaChiPhi { get; set; }
        public string TenChiPhi { get; set; }
        public Nullable<decimal> PhiPhatSinh { get; set; }
        public string Mota { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public int STT { get; set; }
    }
}
