//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HoaDon
    {
        public string SoHopDong { get; set; }
        public string SoHoaDon { get; set; }
        public Nullable<int> TongSoXeThue { get; set; }
        public Nullable<decimal> SoTienTraTruoc { get; set; }
        public Nullable<decimal> SoTienConLai { get; set; }
        public Nullable<decimal> TongThanhToan { get; set; }
        public int STT { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual HopDong HopDong { get; set; }
    }
}
