//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HopDong
    {
        public int SoCTHopDong { get; set; }
        public string SoHopDong { get; set; }
        public string MaLoaiXe { get; set; }
        public string MaXe { get; set; }
        public Nullable<int> QuaDem { get; set; }
        public Nullable<int> SoLuongNguoi { get; set; }
        public System.DateTime NgayDi { get; set; }
        public System.DateTime NgayVe { get; set; }
        public Nullable<System.DateTime> GioDon { get; set; }
        public string DiaDiemDon { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string MaChiPhi { get; set; }
        public string MaTaiXe { get; set; }
        public string BienSoXe { get; set; }
        public string HuongDanVien { get; set; }
        public string MaCongTy { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string PhuXe { get; set; }
        public string TaiXeNgoai { get; set; }
    
        public virtual CongTy CongTy { get; set; }
        public virtual HopDong HopDong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
