//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public HopDong()
        {
            this.CT_HoaDon = new HashSet<CT_HoaDon>();
            this.CT_HopDong = new HashSet<CT_HopDong>();
        }
    
        public string SoHopDong { get; set; }
        public Nullable<System.DateTime> NgayLapHD { get; set; }
        public string MaLoTrinh { get; set; }
        public string MaKH { get; set; }
        public string MaNV { get; set; }
        public string MaHinhThucThue { get; set; }
        public string MaHinhThucThanhToan { get; set; }
        public string MaTrangThai { get; set; }
        public Nullable<decimal> SoTienTraTruoc { get; set; }
        public Nullable<decimal> SoTienConLai { get; set; }
        public Nullable<decimal> GiamGia { get; set; }
        public string GhiChu { get; set; }
        public int STT { get; set; }
        public string MaChiPhi { get; set; }
        public string SoLuongCP { get; set; }
    
        public virtual ICollection<CT_HoaDon> CT_HoaDon { get; set; }
        public virtual ICollection<CT_HopDong> CT_HopDong { get; set; }
        public virtual HinhThucThanhToan HinhThucThanhToan { get; set; }
        public virtual HinhThucThue HinhThucThue { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual LoTrinh LoTrinh { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual TrangThaiHopDong TrangThaiHopDong { get; set; }
    }
}
