//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.HopDongs = new HashSet<HopDong>();
        }
    
        public string MaKH { get; set; }
        public string MaLoaiKH { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string Email { get; set; }
        public string TenKH { get; set; }
        public string TenCongTy { get; set; }
        public string DiaChiKH { get; set; }
        public string CMND { get; set; }
        public string SDT { get; set; }
        public string SDTCongTy { get; set; }
        public string GhiChu { get; set; }
        public string DiaChiCongTy { get; set; }
        public string NguoiLienHe { get; set; }
        public Nullable<decimal> GiamGia { get; set; }
        public string MaSoThue { get; set; }
        public Nullable<bool> Dang { get; set; }
        public int STT { get; set; }
    
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<HopDong> HopDongs { get; set; }
        public virtual LoaiKhachHang LoaiKhachHang { get; set; }
    }
}
