//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiAction
    {
        public LoaiAction()
        {
            this.PhanQuyens = new HashSet<PhanQuyen>();
        }
    
        public int MaAction { get; set; }
        public string TenAction { get; set; }
        public string Mota { get; set; }
        public string UrlAction { get; set; }
        public string MaController { get; set; }
    
        public virtual LoaiController LoaiController { get; set; }
        public virtual ICollection<PhanQuyen> PhanQuyens { get; set; }
    }
}
