//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiXe
    {
        public LoaiXe()
        {
            this.BangGias = new HashSet<BangGia>();
            this.Xes = new HashSet<Xe>();
        }
    
        public string MaLoaiXe { get; set; }
        public string TenLoaiXe { get; set; }
        public Nullable<bool> Dang { get; set; }
        public int STT { get; set; }
    
        public virtual ICollection<BangGia> BangGias { get; set; }
        public virtual ICollection<Xe> Xes { get; set; }
    }
}
