//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiController
    {
        public LoaiController()
        {
            this.LoaiActions = new HashSet<LoaiAction>();
        }
    
        public string MaController { get; set; }
        public string TenController { get; set; }
        public string Icon { get; set; }
        public int STT { get; set; }
    
        public virtual ICollection<LoaiAction> LoaiActions { get; set; }
    }
}
