//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiBang
    {
        public LoaiBang()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public string MaBang { get; set; }
        public string TenBang { get; set; }
        public string MoTa { get; set; }
        public int STT { get; set; }
    
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
