//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luong
    {
        public Luong()
        {
            this.LoaiNhanViens = new HashSet<LoaiNhanVien>();
        }
    
        public string MaLuong { get; set; }
        public Nullable<decimal> Luong1 { get; set; }
        public int STT { get; set; }
    
        public virtual ICollection<LoaiNhanVien> LoaiNhanViens { get; set; }
    }
}
