//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.CT_HopDong = new HashSet<CT_HopDong>();
            this.HoaDons = new HashSet<HoaDon>();
            this.HopDongs = new HashSet<HopDong>();
            this.PhieuChis = new HashSet<PhieuChi>();
            this.PhieuThus = new HashSet<PhieuThu>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
        }
    
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string CMND { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<bool> Dang { get; set; }
        public string MaLoaiNV { get; set; }
        public string SDT { get; set; }
        public Nullable<decimal> LuongThuong { get; set; }
        public string ThongTinKhac { get; set; }
        public string MaBang { get; set; }
        public string Status { get; set; }
        public string MaTinh { get; set; }
        public Nullable<System.DateTime> NgayNghi { get; set; }
        public Nullable<int> SoLan { get; set; }
        public Nullable<System.DateTime> ThoiGianGanDay { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string Email { get; set; }
        public string MaSoThue { get; set; }
        public int STT { get; set; }
        public Nullable<System.DateTime> NgayHethan { get; set; }
        public string GPLX { get; set; }
    
        public virtual ICollection<CT_HopDong> CT_HopDong { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<HopDong> HopDongs { get; set; }
        public virtual LoaiBang LoaiBang { get; set; }
        public virtual LoaiNhanVien LoaiNhanVien { get; set; }
        public virtual Tinh_TP Tinh_TP { get; set; }
        public virtual ICollection<PhieuChi> PhieuChis { get; set; }
        public virtual ICollection<PhieuThu> PhieuThus { get; set; }
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
    }
}
