//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public string MaQuyen { get; set; }
        public int MaAction { get; set; }
        public string MoTa { get; set; }
    
        public virtual LoaiAction LoaiAction { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
