//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyThueXeEntities : DbContext
    {
        public QuanLyThueXeEntities()
            : base("name=QuanLyThueXeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BangGia> BangGias { get; set; }
        public DbSet<ChiPhiPhatSinh> ChiPhiPhatSinhs { get; set; }
        public DbSet<ChiTietChiPhiPhatSinh> ChiTietChiPhiPhatSinhs { get; set; }
        public DbSet<CongTy> CongTies { get; set; }
        public DbSet<CT_HoaDon> CT_HoaDons { get; set; }
        public DbSet<CT_HopDong> CT_HopDongs { get; set; }
        public DbSet<HinhThucThanhToan> HinhThucThanhToans { get; set; }
        public DbSet<HinhThucThue> HinhThucThues { get; set; }
        public DbSet<HoaDon> HoaDons { get; set; }
        public DbSet<HopDong> HopDongs { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<LoaiAction> LoaiActions { get; set; }
        public DbSet<LoaiBang> LoaiBangs { get; set; }
        public DbSet<LoaiController> LoaiControllers { get; set; }
        public DbSet<LoaiKhachHang> LoaiKhachHangs { get; set; }
        public DbSet<LoaiNhanVien> LoaiNhanViens { get; set; }
        public DbSet<LoaiXe> LoaiXes { get; set; }
        public DbSet<LoTrinh> LoTrinhs { get; set; }
        public DbSet<Luong> Luongs { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<PhanQuyen> PhanQuyens { get; set; }
        public DbSet<PhieuChi> PhieuChis { get; set; }
        public DbSet<PhieuThu> PhieuThus { get; set; }
        public DbSet<Quyen> Quyens { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TaiKhoan> TaiKhoans { get; set; }
        public DbSet<ThuongHieuXe> ThuongHieuXes { get; set; }
        public DbSet<Tinh_TP> Tinh_TPs { get; set; }
        public DbSet<TrangThaiHopDong> TrangThaiHopDongs { get; set; }
        public DbSet<Xe> Xes { get; set; }
    }
}
