//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quyen
    {
        public Quyen()
        {
            this.PhanQuyens = new HashSet<PhanQuyen>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
        }
    
        public string MaQuyen { get; set; }
        public string TenQuyen { get; set; }
        public int STT { get; set; }
    
        public virtual ICollection<PhanQuyen> PhanQuyens { get; set; }
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
    }
}
