//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string TaiKhoanNV { get; set; }
        public string MatKhau { get; set; }
        public string MaNV { get; set; }
        public string MaQuyen { get; set; }
        public int STT { get; set; }
        public Nullable<bool> Online { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
