//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThueXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuongHieuXe
    {
        public ThuongHieuXe()
        {
            this.Xes = new HashSet<Xe>();
        }
    
        public string MaThuongHieu { get; set; }
        public string TenThuongHieu { get; set; }
        public int STT { get; set; }
    
        public virtual ICollection<Xe> Xes { get; set; }
    }
}
